### ISSUE TITLE
The interpreter changes some values when they have a long number

### ISSUE THREAD

**Issue by Jhonsensf** [runnerty/runnerty#100]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/Coderty/runnerty/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Using a param which contanis a long number in the string the interpreter makes changes on it. Like expounding the number.

**Expected behavior**
It should pass the string as it is defined on the param

**Minimal reproduction of the problem with instructions**
For example, using de @runnerty-trigger-twitter 
```
"triggers": [
    {
      "id":"twitter_default",
      "type":"@runnerty-trigger-twitter",
      "consumerKey":"1234acb",
      "consumerSecret":"1234acb",
      "accessToken":"123431241244523453245234523-HsmfirenfmvlSxbfDsdffvXfasdfgbZCfgh",
      "accessTokenSecret":"1234acb"
    }
```

the `"accessToken":"123431241244523453245234523-HsmfirenfmvlSxbfDsdffvXfasdfgbZCfgh",` is truncated to other number

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Runnerty version:** 2.0.1

* **Operation system:** MacOs

* **Node version:** `node --version` =v8.7.0

**Comment by CarlosCarmona** [comment]
Thank you @Jhonsensf this is fixed in 2.0.2! https://github.com/runnerty/runnerty/commit/04f764e2543d31cd34faf315dbc884795c482154
