### ISSUE TITLE
Remove unused property in config

### ISSUE THREAD

**Issue by Jhonsensf** [runnerty/runnerty#121]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/Coderty/runnerty/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
In the config's schema file there is a property called `additionalProperties ` It has never been used and it will not be.

**Expected behavior**
It's better to remove it because it is confusing.

**Please tell us about your environment:**

* **Runnerty version:** 2.1.3

* **Operation system:** macOS High Sierra 10.13.5

* **Node version:** `node --version` = 10.0.0

**Comment by CarlosCarmona** [comment]
These fix have been included in version 2.6.0
Thanks!
