### ISSUE TITLE
Use standard Node.js module resolution paths

### ISSUE THREAD

**Issue by alexfernandez** [runnerty/runnerty#127]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/Coderty/runnerty/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When starting Runnerty in a given directory, it requires to have `node_modules` with all dependencies in that same directory.

**Expected behavior**
It would be great if Runnerty used the same directory resolution algorithm as [Node.js](https://nodejs.org/api/modules.html). Apparently there is a function `require.resolve()` to do it.

**Minimal reproduction of the problem with instructions**
I have the following directory structure:
```
package.json
node_modules
config
 |- server1
 | |- config.json
 | \- plan.json
 \- server2
...
```

Dependencies are installed in the root, and each server has its own tasks. If I try to start runnerty from `config/server1`, I get an error since it cannot find `node_modules`.

**What is the motivation / use case for changing the behavior?**

Being able to have multiple task definitions in different directories without duplicating a `package.json` and `node_modules`.

**Please tell us about your environment:**

Not relevant.

* **Runnerty version:** 2.x

* **Operation system:** Not relevant

* **Node version:** `node --version` = not relevant.

**Comment by alo** [comment]
Closed on #128
