### ISSUE TITLE
Slack: Can only register with @coderty.com email?

### ISSUE THREAD

**Issue by IngwiePhoenix** [runnerty/runnerty#143]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] support request => Please do not submit support request here, instead see https://github.com/Coderty/runnerty/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I wanted to ask a question, but Slack required me to have a `@coderty.com` email address - which I do not have and do not plan to get. I have a `@googlemail.com` address instead.

**Expected behavior**
I expected to be able to log in to ask my question(s).

**Minimal reproduction of the problem with instructions**
- Visit `CONTRIBUTING.md`
- Click on the Slack chat URL (runnerty.slack.com)
- Read the text beneath the login form.

**Please tell us about your environment:**
OS: Windows 10 (1909)
Browser: Opera GX
E-Mail Provider: Google Mail

* **Operation system:**
Probably all of them?

---

Now, joke aside. I am quite interested in this project because all I need is a way to launch multiple processes (microservices) that depend on a master process running a RPC server. Since this issue tracker is more for issues than not, I decided to treat the inability of asking my question as such ;). Hope to ask my questions soon!

Kind regards,
Ingwie

**Comment by alo** [comment]
Hi! Thanks for reporting the issue. The link is broken, here you have a new one! 

https://join.slack.com/t/runnerty/shared_invite/enQtMTgxNDQ2NTk2NTk3LTg5Y2JjNzBlMTU3OGY5NDYxYjRiMmQ1Y2ZjNDVjMDk2NmM1MzNhZDYyOGZjOWZhNjFjZDE4MDYxODg0NGJkY2I

We have to change it in runnerty.io

**Comment by IngwiePhoenix** [comment]
Thank you for the reply!

Yes, you probably should :)
