### ISSUE TITLE
Interpreter-functions: more date functions

### ISSUE THREAD

**Issue by pakitovic** [runnerty/runnerty#144]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/Coderty/runnerty/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Needed a few more date functions:

`@LAST_DAY(@GETDATE('YYYY-MM-DD'))`
`@DATE_FORMAT(@GV(LOAD_DATE), 'DD-MM-YYYY', 'months', -1)`

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Runnerty version:** 2.5.1

* **Operation system:** MacOS

* **Node version:** `node --version` = 10.17

**Comment by CarlosCarmona** [comment]
These features have been included in version 2.6.0
Thanks for the suggestion!
