### ISSUE TITLE
The documentation is missing

### ISSUE THREAD

**Issue by joviwap** [runnerty/runnerty#3]
Please, could you upload some info. I really want to try Runnerty but it is difficult without any documentation.

Thanx :)

**Comment by alo** [comment]
Hi @joviwap! 
We are working hard to have the docs as soon as possible. I can not assure you but we hope to have a first version for the end of the week! 

Thanks!

**Comment by CarlosCarmona** [comment]
Hi @joviwap!
We just released 1.0.0 version.
All the docs are [http://docs.runnerty.io](url)
Enjoy!

**Comment by joviwap** [comment]
Awesome! I'll check it ASAP 😄
